GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzg1MjkxNDQsImV4cCI6MTczODUyOTE1OSwiYXVkIjoiNjc5ZmQxZDVjZTM2OTU5NmZjZmE3ZDA5IiwiaXNzIjoidmVkc2hhcm1hLm5ldGxpZnkuYXBwIn0.uUflwTrckemZMTO4dpLzFVNQiWwy7MYZadhR_-xOCsc

###
GET http://localhost:3000/abc_xyz

### Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "yourstr123@gmail.com",
    "password": "123456"
}

### Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "yourstr23@gmail.com",
    "password": "123456"
}

### Refresh Token Route
POST http://localhost:3000/auth/refresh-token

### Logout Route
DELETE http://localhost:3000/auth/logout